### ISSUE TITLE
BACKEND -- INCLUDE BUTTON -- Quiz

### ISSUE THREAD

**Issue by Anastasiyavyp** [becodeorg/Learning2gether-platform#223]
For the front-end to be able to create extra classes for the lay-out, they need to access buttons of froms/inputfields in symfony.
To do this, the backend code needs to be adjusted with the "include" code.

QUIZ
- check which buttons need to change, probably:
- edit button
- start quiz
- save button / update

**Comment by joostvannieu** [comment]
Checked, and I believe it shouldn't cause any styling issues for the front-end
