### ISSUE TITLE
Upload LM - IMG preview

### ISSUE THREAD

**Issue by ghost** [becodeorg/Learning2gether-platform#338]
no preview yet

**Comment by pixeline** [comment]
weirdly enough, doing

```bash
sudo ./bin/console liip:imagine:cache:resolve 3aca96dd34de5953d602464df87e7863.jpeg --filter=learningModuleImage
````

via ssh fixes the image. It looks like the page needs to be refreshed for the image to be available in the cache. So the Ajax upload is not adapted here I guess?

**Comment by janvdv96** [comment]
This was the ticket to create an image preview when uploading an image to the module creation page.
This was so the partner can see a preview of the file they are preparing to upload.
I don't understand why the image should be cached ?
[The javascript i wrote for this ticket](https://github.com/becodeorg/Learning2gether-platform/blob/master/public/assets/js/UploaderPreviewScript.js)

**Comment by pixeline** [comment]
> This was the ticket to create an image preview when uploading an image to the module creation page.
> This was so the partner can see a preview of the file they are preparing to upload.
> I don't understand why the image should be cached ?
> [The javascript i wrote for this ticket](https://github.com/becodeorg/Learning2gether-platform/blob/master/public/assets/js/UploaderPreviewScript.js)
@janvdv96  Ah indeed, the ticket wasn't very clear so I assumed it was related to the actual upload. So wrong, ticket, sorry! Feel free to unsubscribe if you are, I've un-assigned you :-)
